import type { Metadata } from "next";
import { Smooch_Sans } from "next/font/google";
import Header from "./components/header/Header";
import "./globals.css";

const smoochSans = Smooch_Sans({
  variable: "--font-smooch-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${smoochSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
